Les-3/task-3-oop-principles complete
SergeyPolud/AQA_Lab-1 pull request #6
Opened 2022-02-11 21:00 UTC by SergeyPolud

2022-02-15 12:34 UTC, AlexanderHoha commented on EmployeesAndCandidates/Candidate.cs
> +public class Candidate : IUser
Можно сделать базовый класс Person и туда вынести общие поля

2022-02-16 16:04 UTC, mashadolya requested changes

2022-02-16 16:04 UTC, mashadolya commented on EmployeesAndCandidates/IUser.cs
> +    public void PrintUserInformation();
по умолчанию паблик

2022-02-16 16:04 UTC, mashadolya commented on EmployeesAndCandidates/UserFactory.cs
> +        var employee = generator.Generate();
Generate умеет принимать число необходимого количества объектов для создания 
Используй вызова метода в цикле

2022-02-17 22:22 UTC, SergeyPolud commented on EmployeesAndCandidates/CandidateReportGenerator.cs
> +        var sorted = users.OfType<Candidate>().OrderBy(c=>c.Position).ThenByDescending(c => c.Salary);
А по таске же, вроде нужно один интерфейс для двух генераторов репортов, получается что и один метод должен быть? Или я здесь туплю

2022-02-22 08:41 UTC, mashadolya approved these changes

2022-02-22 08:41 UTC, mashadolya commented on EmployeesAndCandidates/CandidateReportGenerator.cs
> +    private static void WriteEmployeeInfo(Candidate candidate)
где пустая строка?

2022-02-22 08:41 UTC, mashadolya commented on EmployeesAndCandidates/UsersGenerator.cs
> +    private const int MaxCount = 10;
ну как то. странно зашивать это число в класс
лучше передавать с мейна

2022-02-22 18:57 UTC, merged